-- 1. Table for tracking Active Game Servers
create table if not exists game_servers (
  id text primary key, -- Roblox JobId
  status text not null, -- 'active', 'shutdown'
  region text,
  place_version text,
  fps real,
  ping integer,
  player_count integer,
  max_players integer,
  last_heartbeat timestamp with time zone default timezone('utc'::text, now()),
  started_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS (Row Level Security) if needed, but for now we'll allow anon reads if we want or just service role
alter table game_servers enable row level security;

-- Policy to allow authenticated users (staff) to view servers
create policy "Allow staff to view servers"
  on game_servers for select
  using ( auth.role() = 'authenticated' );

-- Policy to allow service_role (API) to insert/update
-- (Implicitly allowed for service_role, but if using anon client for reporting, need insert)
create policy "Allow internal insert/update"
    on game_servers for all
    using ( true )
    with check ( true ); 


-- 2. Table for Server Console Logs
create table if not exists server_logs (
    id bigint generated by default as identity primary key,
    server_id text references game_servers(id) on delete cascade,
    timestamp timestamp with time zone default timezone('utc'::text, now()),
    message text,
    msg_type text -- 'Output', 'Info', 'Warning', 'Error'
);

alter table server_logs enable row level security;

create policy "Allow staff to view logs"
  on server_logs for select
  using ( auth.role() = 'authenticated' );

create policy "Allow internal insert logs"
    on server_logs for insert
    with check ( true );
